MonkeyGameStore/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
import adminpanel.urls

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin_panel/', include('adminpanel.urls')),
    path('',include('clientpanel.urls')),
    path('',include('cart.urls')),
    path('',include('orders.urls')),
    path('',include('offerss.urls')),
    path('',include('coupons.urls')),
    path('', include('salesreport.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminpanel/urls.py
from urllib.parse import urlparse

from django.urls import path
from adminpanel import views
from adminpanel.views import (admin_dashboard_view,admin_login_view,admin_logout_view,
admin_user_type_view,admin_customer_list_view,customer_block_view,order_list_view,
order_detail_view,order_weekly,order_monthly,revenue_weekly,revenue_monthly)
from products.views import (admin_category_list_view,admin_addcategory_view,admin_category_edit_view,admin_addgame_view,admin_listgame_view,admin_editgame_view,
                            admin_category_disable,subcategory_add_view,game_block_view,delete_category,delete_game)

urlpatterns = [
    path('', admin_dashboard_view, name='admin_dashboard'),
    path('login/', admin_login_view, name='admin_login'),
    path('logout/', admin_logout_view, name='admin_logout'),

    #---------------------------User/customer/staff-----------------------------

    path('users',admin_user_type_view, name='admin_user_type'),
    path('users/customers',admin_customer_list_view, name='customer_list'),
    path('users/customers/<id>/block/',customer_block_view, name='blockcustomer'),
  


    #---------------------------Category----------------------------------------------

    path('categories/',admin_category_list_view, name='admin_categorylist'),
    path('categories/addcategory/',admin_addcategory_view, name='admin_addcategory'),
    path('categories/<slug>/edit/',admin_category_edit_view, name='admin_editcategory'),
    path('categories/<slug>/disable/',admin_category_disable, name='disablecategory'),
    path('categories/<slug>/addsubcategory/',subcategory_add_view, name='add_subcategory'),
    path('categories/<slug>/delete/',delete_category,name='deletecategory'),




    #---------------------------Game-------------------------------------------------
    path('games/addgame/',admin_addgame_view,name='admin_addgame'),
    path('games/',admin_listgame_view,name='admin_gamelist'),
    path('games/<id>/edit/',admin_editgame_view,name='admin_editgame'),
    path('games/<id>/disable/',game_block_view,name='disablegame'),
    path('games/<id>/delete/',delete_game,name='deletegame'),
    
    # path('users/admins', admin_staff_list_view,name ='admin_staff_list_view'),

    #------------------------------Orders-----------------------------------------
    path('orders/',order_list_view,name='admin_orderlist'),
    path('orders/detail/<id>/',order_detail_view,name = 'admin_orderdetail'),

    #------------------------------Charts---------------------------------------
    path('weeklyorders/',order_weekly,name='weeklyorders'),
    path('monthlyorders/',order_monthly,name='monthlyorders'),
    path('weeklyrevenue/',revenue_weekly,name='weeklyrevenue'),
    path('monthlyrevenue/',revenue_monthly,name='monthlyrevenue'),

]




cart/urls.py
from django.urls import path
from cart.views import (
cart_view,
add_cart_item,
cart_counter,
quantity_update,
view_redeemable_coupons
)

urlpatterns = [
    path('cart/',cart_view,name='cart'),
    path('cart/update/',add_cart_item,name='update_cart'),
    path('cart/counter/',cart_counter,name='cart-counter'),
    path('cart/updatequantity/',quantity_update, name='quantity-update'),
    path('cart/view_redeemable_coupons/',view_redeemable_coupons,name='usercoupons'),
    
]

adminpanel/models.py
from django.db import models

# Create your models here.

adminpanel/forms.py
from django import forms
from django.forms import SelectDateWidget


class ReportFiltersForm(forms.Form):
    start_date = forms.DateField(input_formats='%Y,%m,%d',required=False)
    end_date = forms.DateField(input_formats='%Y,%m,%d',required=False)
    class Meta:
        fields=('start_date','end_date')
        widgets={
            'start_date': forms.DateTimeInput(attrs=dict(type='datetime-local')),
            'end_date': forms.DateTimeInput(attrs=dict(type='datetime-local')),
        }

adminpanel/views.py
from ast import Not
from calendar import calendar, month
from calendar import day_name

import datetime
from datetime import date, timedelta,datetime
import decimal

from django.http import JsonResponse
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from accounts.models import MyUser
from adminpanel.forms import ReportFiltersForm
from coupons.models import Coupon
from orders.models import Order

from django.views.decorators.cache import never_cache
from orders.forms import OrderStatusChangeForm
from django.utils import timezone
from django.db.models import Sum

from products.models import Game



# Create your views here.

@never_cache
@user_passes_test(lambda u:u.is_superuser, login_url="admin_login")
def admin_dashboard_view(request):
    greeting = "Welcome to admin panel"
    
    completed_orders = Order.objects.filter(status='Completed').count()
    total_revenue = Order.objects.filter(status='Completed').aggregate(Sum('db_total'))['db_total__sum']
    top_game = Game.objects.all().order_by('-salecount')[0]
    orders = Order.objects.filter(status='Completed')
    tp_gm_rev=decimal.Decimal(0.00)
    for order in orders:
        for item in order.items.all():
            if item.game == top_game:
                tp_gm_rev += item.item_total
    tp_cp_disc = 0
    top_coupon = Coupon.objects.all().order_by('-usage_count')[0]
    for order in orders:
        if order.applied_coupon is not None:
            if order.applied_coupon.coupon == top_coupon:
                tp_cp_disc += order.coupon_discount
    users = MyUser.objects.filter(is_verified=True)

    highest_user_rev = decimal.Decimal(0.00)
    for user in users:
        user_revenue = user.orders.filter(status='Completed').aggregate(Sum('db_total'))['db_total__sum'] or 0.00
        if user_revenue > highest_user_rev:
            highest_user_rev = user_revenue
            top_user = user.username
    games = Game.objects.all()
    highest_game_rev = decimal.Decimal(0.00)
    for game in games:
        single_game_rev = decimal.Decimal(0.00)
        for sale in game.order_items.all():
            if sale.order.status == 'Completed':
                single_game_rev += sale.item_total
        if single_game_rev > highest_game_rev:
            highest_game_rev = single_game_rev
            highest_game_rev_obj = game
    form =ReportFiltersForm()
    
    context= {
        'highest_game_rev':highest_game_rev,
        'highest_game_rev_obj':highest_game_rev_obj,
        'top_user':top_user,
        'top_user_rev':highest_user_rev,
        'tp_cp_disc':tp_cp_disc,
        'top_coupon':top_coupon,
        'tp_gm_rev':tp_gm_rev,
        'top_game': top_game,
        'total_revenue':total_revenue,
        'completed_orders':completed_orders,
        'form' : form,
        'greeting': greeting,
    }
    return render( request,'adminpanel/admin_dashboard_content.html', context )

def revenue_weekly(request):
    weekly_revenue = []
    week_days = []
    sum=0
    for i in reversed(range(0,7)):
        daily_revenue = Order.objects.filter(status='Completed',created_at__date=date.today()-timedelta(days=i)).aggregate(Sum('db_total'))['db_total__sum'] or 0.00
        # daily_orders = Order.objects.filter(status='Completed',created_at__date=date.today()-timedelta(days=i)).count()
        sum = decimal.Decimal(decimal.Decimal(sum)+decimal.Decimal(daily_revenue))
        weekly_revenue.append(daily_revenue)
        day = date.today()-timedelta(days=i)
        dayname = day_name[day.weekday()]
        week_days.append(dayname)

    labels = week_days
    chartlabel = "Revenue"
    data = weekly_revenue
    
    return JsonResponse(data={
        'sum':sum,
        'labels': labels,
        'chartlabel': chartlabel,
        'data': data,
    })

def revenue_monthly(request):
    weekly_orders = []
    week_days = []
    sum=0.00
    for i in reversed(range(0,28,7)):
        daily_orders = Order.objects.filter(status='Completed',created_at__range=[datetime.now(tz=timezone.utc)-timedelta(days=i+7),datetime.now(tz=timezone.utc)-timedelta(days=i)]).aggregate(Sum('db_total'))['db_total__sum'] or 0.00
        sum = decimal.Decimal(decimal.Decimal(sum)+decimal.Decimal(daily_orders))
        weekly_orders.append(daily_orders)
        day = date.today()-timedelta(days=i+7),date.today()-timedelta(days=i)
        # dayname = day_name[day.weekday()]
        week_days.append(day)
  
    labels = week_days
    chartlabel = "Revenue"
    data = weekly_orders
    
    return JsonResponse(data={
        'sum':sum,
        'labels': labels,
        'chartlabel': chartlabel,
        'data': data,
    })

def order_weekly(request):
    weekly_orders = []
    week_days = []
    sum = 0
    for i in reversed(range(0,7)):
        # daily_orders = Order.objects.filter(status='Completed',created_at__date=date.today()-timedelta(days=i)).aggregate(Sum('db_total'))['db_total__sum'] or 0.00
        daily_orders = Order.objects.filter(status='Completed',created_at__date=date.today()-timedelta(days=i)).count()
        sum = sum+daily_orders
        weekly_orders.append(daily_orders)
        day = date.today()-timedelta(days=i)
        dayname = day_name[day.weekday()]
        week_days.append(dayname)

    labels = week_days
    chartlabel = "Orders"
    data = weekly_orders
    
    return JsonResponse(data={
        'sum':sum,
        'labels': labels,
        'chartlabel': chartlabel,
        'data': data,
    })
    
def order_monthly(request):
    weekly_orders = []
    week_days = []
    sum = 0
    for i in reversed(range(0,28,7)):
        daily_orders = Order.objects.filter(status='Completed',created_at__range=[datetime.now(tz=timezone.utc)-timedelta(days=i+7),datetime.now(tz=timezone.utc)-timedelta(days=i)]).count()
        weekly_orders.append(daily_orders)
        sum=sum+daily_orders
        day = date.today()-timedelta(days=i+7),date.today()-timedelta(days=i)
        # dayname = day_name[day.weekday()]
        week_days.append(day)
  
    labels = week_days
    chartlabel = "Orders"
    data = weekly_orders
    
    return JsonResponse(data={
        'sum':sum,
        'labels': labels,
        'chartlabel': chartlabel,
        'data': data,
    })

def admin_login_view(request):
    
    if request.user.is_authenticated and request.user.is_superuser:
        return redirect('admin_dashboard')
    
    else:
        if request.method == 'POST':
            email = request.POST.get('email')
            password = request.POST.get('password')

            user = authenticate(request, email = email, password = password)
            if user is not None:
                login(request,user)
                return redirect('admin_dashboard')
            
            else:
                messages.error(request, "email/password incorrect!!! ")
    context = {}
    return render(request,'adminpanel/admin_login.html', context)

def admin_logout_view(request):
    logout(request)
    return redirect('admin_login')


@never_cache
@user_passes_test(lambda u:u.is_superuser, login_url="admin_login")
def admin_user_type_view(request):
    context = {}
    return render(request,'admin_user_type.html',context)


@never_cache
@user_passes_test(lambda u:u.is_superuser, login_url="admin_login")
def admin_customer_list_view(request):                                      #block/unblock here (edit view next week)
    customers = MyUser.objects.all()
    context = {'customers':customers,}
    return render(request,'adminpanel/admin_customer_list.html',context)



@never_cache
@user_passes_test(lambda u:u.is_superuser, login_url="admin_login")
def customer_block_view(request,id):
    block_user = MyUser.objects.get(id=id)

    if block_user.is_blocked:
        block_user.is_blocked = False
        block_user.save()
        messages.error(request,f"{block_user.username} unblocked successfuly")
    else:
        block_user.is_blocked =True
        block_user.save()
        messages.success(request,f"{block_user.username} blocked successfuly")
    return redirect('customer_list')    
   






@never_cache
@user_passes_test(lambda u:u.is_superuser, login_url="admin_login")
def order_list_view(request):
    orders = Order.objects.all().order_by('-created_at')
    
    context = {
        'orders' : orders,
    }

    return render(request,'adminpanel/admin_orderlist.html',context)



@never_cache
@user_passes_test(lambda u:u.is_superuser, login_url="admin_login")
def order_detail_view(request,id):
    try:
        order = Order.objects.get(id=id)
    except:
        messages.error(request,"Order not found")
        return redirect('admin_orderlist')
    
    if request.method == 'POST':
        form = OrderStatusChangeForm(id,request.POST,instance = order,)
        if form.is_valid():
            order.save()
            return redirect('admin_orderdetail',id)
    else:
        form = OrderStatusChangeForm(id,instance = order,)
        
    
    context = {
        'form' : form,
        'order' : order,
    }
    return render(request,'adminpanel/order_detail.html', context)



templates/adminpanel/admin_addcategory.html




{% extends 'adminpanel/admin_dashboard.html' %}
{%load crispy_forms_tags %} 
{% load static %}
{% block dynamic_css %}<link rel="stylesheet" type="text/css" href="{% static "/styles/clientpanel/login.css" %}"> {% endblock dynamic_css %}


{% block dynamic %}

<main class="container-fluid" style="width:100%;">
  <div class="col-12 col-sm-7 col-md-6 col-lg-4">
    <form action="" method="post">
      {% csrf_token %}
      
  

     
      <h1 class="h3 mb-3 fw-normal"><u>Add Category</u></h1>
      
      

     
      
        {{form|crispy}}
        
        <button class="w-10 btn btn-lg btn-primary mb-3 signbtn fs-6" style="margin-left:auto;" type="submit">Add New Category</button>
    </form>
  </div>

  </main>
  
  
  


{% endblock dynamic %}







templates/adminpanel/admin_dashboard_content.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block extracss %}<link rel="stylesheet" href="{% static 'styles/admin_dashboard.css' %}">{% endblock extracss %}
{% block dynamic_css %}<link rel="stylesheet" href="{% static 'styles/admin-dashboard.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
{% endblock dynamic_css %}

{% block navbar %}
{% include 'includes/adminpanel/admin_navbar.html' %}
{% endblock navbar %} 


{% block content %} 
<div class="main">
<div class="container-fluid outer-side-container">
  <div class="row flex-nowrap main-container ">
      <div class="col-auto col-md-9 col-lg-9 px-sm-9 px-0 bg-dark left-main-nav ms-2">
          <div class="d-flex flex-column align-items-sm-start pt-2 text-white min-vh-100">
              
              <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-sm-start w-100" id="menu">
                 
                  <li>
                      <a href={% url 'admin_dashboard' %}  class="nav-link px-0 align-middle ">
                          <i class="fs-4 bi-speedometer2"></i> <span class="ms-1  d-sm-inline">Dashboard</span> </a>
                      
                  </li>
                  <li>
                      <a href={% url 'customer_list' %} class="nav-link px-0 align-middle">
                          <i class="fs-4 bi-table"></i> <span class="ms-1 d-sm-inline">Users</span></a>
                  </li>
                  <li>
                      <a href="{% url 'admin_gamelist' %}"  class="nav-link px-0 align-middle ">
                          <i class="fs-4 bi-bootstrap"></i> <span class="ms-1 d-sm-inline">Games</span></a>
                      
                  </li>
                  <li>
                      <a href={% url 'admin_categorylist' %}  class="nav-link px-0 align-middle">
                          <i class="fs-4 bi-grid"></i> <span class="ms-1 d-sm-inline">Categories</span> </a>
                          
                  </li>

                  <li>
                    <a href={% url 'admin_orderlist' %}  class="nav-link px-0 align-middle">
                        <i class="fs-4 bi-grid"></i> <span class="ms-1 d-sm-inline">Orders</span> </a>
                        
                </li>
                <li>
                  <a href={% url 'offerlist' %}  class="nav-link px-0 align-middle">
                      <i class="fs-4 bi-grid"></i> <span class="ms-1 d-sm-inline">Offers</span> 
                  </a> 
                </li>
                <li>
                  <a href={% url 'admin_couponlist' %}  class="nav-link px-0 align-middle">
                      <i class="fs-4 bi-grid"></i> <span class="ms-1 d-sm-inline">Coupons</span> 
                  </a> 
                </li>
                <li>
                  <a href={% url 'salesreport' %}  class="nav-link px-0 align-middle">
                      <i class="fs-4 bi-grid"></i> <span class="ms-1 d-sm-inline">Sales Report</span> 
                  </a> 
                </li>
                  {% comment %} <li>
                      <a href="#" class="nav-link px-0 align-middle">
                          <i class="fs-4 bi-people"></i> <span class="ms-1 d-sm-inline">add more</span> </a>
                  </li> {% endcomment %}
              </ul>
              
          </div>
      </div>
    
  </div>
</div>

  <div class="dynamic"> 
    {% block dynamic %}
    {% comment %} <form action="">
        {% csrf_token %}
        {{form}}
    </form> {% endcomment %}
    <div class="row" style='width:99%;padding-left:1%;'>
      <div class="col-md-3 col-12 card1 d-flex flex-column justify-content-center align-items-center me-3"><span class='fw-bold'>Completed Orders</span><span>{{completed_orders}}</span></div>
      <div class="col-md-3 col-12 card2 d-flex flex-column justify-content-center align-items-center me-3"><span class='fw-bold'>Total Revenue</span><span>₹{{total_revenue}}</span></div>
    </div>
  
    <select id="div-toggle" onchange="helloworld();helloworld2();">
      <option value="lastweek">Last Week</option>
      <option value="lastmonth">Last Month</option>
    </select>
    {% comment %} <div class="row">
      <div class='col-md-1'>
        {{form.start_date|as_crispy_field}}
      </div>
      <div class='col-md-1'>
        {{form.end_date|as_crispy_field}}
      </div>
    </div> {% endcomment %}
    
    <div class='row mb-5' style="width: 99%;">
      <div class='col-lg-6 col-12 d-flex flex-column'><div id="orderheading">Last Week's Orders:</div><canvas id="orderchart" ></canvas></div>
      <div class='col-lg-6 col-12 d-flex flex-column'><div id="revenueheading">Last Week's Revenue:</div><canvas id="revenuechart" ></canvas></div>
    </div>
    <div class="row" style='width:99%;padding-left:1%;'>

      <div class="col-md-3 col-12 card1 d-flex flex-column justify-content-center align-items-center me-3">
        <span class='fw-bold'>Most Sold Game</span>
        <span>{{top_game}}</span>
        <span>Product Keys sold: {{top_game.salecount}}</span>
        <span>Revenue Generated: ₹{{tp_gm_rev}}</span>
      </div>

      <div class="col-md-3 col-12 card2 d-flex flex-column justify-content-center align-items-center me-3">
        <span class='fw-bold'>Most Used Coupon</span>
        <span>{{top_coupon.coupon_code}}</span>
        <span>Discount Given: ₹{{tp_cp_disc}}</span>
      </div>

      <div class="col-md-3 col-12 card1 d-flex flex-column justify-content-center align-items-center me-3">
        <span class='fw-bold'>Most Revenue Generated Game</span>
        <span>👑{{highest_game_rev_obj.title}}👑</span>
        <span>Product Keys sold: {{highest_game_rev_obj.salecount}}</span>
        <span>Revenue Generated: ₹{{highest_game_rev}}</span>
      </div>
      
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.9.1/chart.min.js" integrity="sha512-ElRFoEQdI5Ht6kZvyzXhYG9NqjtkmlkfYk0wr6wHxU9JEHakS7UJZNeml5ALk+8IKlU6jDgMabC3vkumRokgJA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
  {% comment %} $("#id_start_date").flatpickr({
    dateFormat: "Y-m-d",
    }
  );
  $("#id_end_date").flatpickr({
    dateFormat: "Y-m-d",
    }
  ); {% endcomment %}
  window.onload = helloworld();helloworld2();
  function helloworld() {
    let chartStatus = Chart.getChart("orderchart"); // <canvas> id
      if (chartStatus != undefined) {
        chartStatus.destroy();
      }
    var $populationChart = $("#orderchart");
    var value = $('#div-toggle').val();
    if(value == "lastweek"){
      $("#orderheading").html("Last Week's Orders:");
      var current_url = "/admin_panel/weeklyorders/";
    }
    else if(value == "lastmonth"){
      $("#orderheading").html("Last Month's Orders:");
      var current_url = "/admin_panel/monthlyorders/";
    }
    $.ajax({
      url: current_url,
      success: function (data) {
        if(current_url == "/admin_panel/weeklyorders/"){
          $("#orderheading").html(`Last Week's Orders: <b>${data.sum}</b>`);
        }
        else{
          $("#orderheading").html(`Last Month's Orders: <b>${data.sum}</b>`);
        }
        var ctx = $populationChart[0].getContext("2d");

        new Chart(ctx, {
          type: 'line',
          data: {
            labels: data.labels,
            datasets: [{
              label: data.chartlabel,
              data: data.data,
              cubicInterpolationMode: 'monotone',
              backgroundColor: [
              'rgba(255, 99, 132, 0.2)',
              'rgba(54, 162, 235, 0.2)',
              'rgba(255, 206, 86, 0.2)',
              'rgba(75, 192, 192, 0.2)',
              'rgba(153, 102, 255, 0.2)',
              'rgba(255, 159, 64, 0.2)'
                
                ],
              borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1,
              
            }]          
          },
          options: {
            responsive: true,
            legend: {
              position: 'top',
            },
            
          }
        });

      }
    });

  }

  function helloworld2() {
    let chartStatus = Chart.getChart("revenuechart"); // <canvas> id
      if (chartStatus != undefined) {
        chartStatus.destroy();
      }
    var $revenueChart = $("#revenuechart");
    var value = $('#div-toggle').val();
    if(value == "lastweek"){
      $("#revenueheading").html("Last Week's Revenue:");
      var current_url = "/admin_panel/weeklyrevenue/";
    }
    else if(value == "lastmonth"){
      $("#revenueheading").html("Last Month's Revenue:");
      var current_url = "/admin_panel/monthlyrevenue/";
    }
    $.ajax({
      url: current_url,
      success: function (data) {
        if(current_url == "/admin_panel/weeklyrevenue/"){
          $("#revenueheading").html(`Last Week's Revenue: <b>₹${data.sum}</b>`);
        }
        else{
          $("#revenueheading").html(`Last Month's Revenue: <b>₹${data.sum}</b>`);
        }
        
        var ctx = $revenueChart[0].getContext("2d");

        new Chart(ctx, {
          type: 'line',
          data: {
            labels: data.labels,
            datasets: [{
              label: data.chartlabel,
              data: data.data,
              cubicInterpolationMode: 'monotone',
              backgroundColor: [
              'rgba(255, 99, 132, 0.2)',
              'rgba(54, 162, 235, 0.2)',
              'rgba(255, 206, 86, 0.2)',
              'rgba(75, 192, 192, 0.2)',
              'rgba(153, 102, 255, 0.2)',
              'rgba(255, 159, 64, 0.2)'
                
                ],
              borderColor: [
              'rgba(255, 206, 86, 1)',
                
                'rgba(54, 162, 235, 1)',
                'rgba(255, 99, 132, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1,
              
            }]          
          },
          options: {
            responsive: true,
            legend: {
              position: 'top',
            },
            
          }
        });

      }
    });

  }
  
    </script>
</script>
{% comment %} <script>
  $(function () {
    alert('sfsfsfsf');
    var $monthlyorders = $("#monthlyOrders");
    $.ajax({
      url: "/admin_panel/weeklyorders/",
      success: function (data) {

        var ctx = $monthlyorders[0].getContext("2d");

        new Chart(ctx, {
          type: 'line',
          data: {
            labels: data.labels,
            datasets: [{
              label: data.chartlabel,
              data: data.data,
              cubicInterpolationMode: 'monotone',
              backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
                ],
              borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
                ],
                borderWidth: 1,
              
            }]          
          },
          options: {
            responsive: true,
            legend: {
              position: 'top',
            },
            
          }
        });

      }
    });

  }); {% endcomment %}

</script>
    
    {% endblock dynamic %}
</div>

</div>

{% endblock content %}


templates/adminpanel/admin_editcategory.html




{% extends 'adminpanel/admin_dashboard.html' %}
{%load crispy_forms_tags %} 
{% load static %}
{% block dynamic_css %}<link rel="stylesheet" type="text/css" href="{% static "/styles/clientpanel/login.css" %}"> {% endblock dynamic_css %}
{% block style %}
<style>
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }
</style>
{% endblock style %}

{% block dynamic %}



<main class="container-fluid d-flex justify-content-between" style="width:100%;">
  <div class="col-12 col-sm-7 col-md-6 col-lg-4">
    <form action="" method="post">
      {% csrf_token %}
      
      <h1 class="h3 mb-3 fw-normal">Update "{{category_edit}}"</h1>
        {{form|crispy}}
        <button class="w-30 btn btn-lg btn-primary mb-3 signbtn" type="submit">Update</button>
    </form>
  </div>  
  <div class='sub-category ms-5' style="box-shadow: 0px 0px 10px white;border-radius:10px;width:30%;margin-right:30%;padding:1%;">
    <h2>Sub-Categories</h2>
    <a href="/admin_panel/categories/{{category_edit.get_absolute_url}}/addsubcategory/">
      <button type="button" class="btn btn-link btn-sm btn-rounded btn-unblock">
          Add Sub-category
      </button>
      </a> 
  {% for sub_category in category_edit.sub_categories.all %}
                
                  <ul>
                    <li>
                      <a style='text-decoration:none;' href="{% url 'admin_editcategory' sub_category.slug %} ">{{ sub_category.name}}</a>
                    </li>
                  </ul>
                  
                  <br>
                {% endfor %}
              </div>

                
                
              </main>
{% endblock dynamic %}





