MonkeyGameStore/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
import adminpanel.urls

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin_panel/', include('adminpanel.urls')),
    path('',include('clientpanel.urls')),
    path('',include('cart.urls')),
    path('',include('orders.urls')),
    path('',include('offerss.urls')),
    path('',include('coupons.urls')),
    path('', include('salesreport.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from cart.views import (
cart_view,
add_cart_item,
cart_counter,
quantity_update,
view_redeemable_coupons
)

urlpatterns = [
    path('cart/',cart_view,name='cart'),
    path('cart/update/',add_cart_item,name='update_cart'),
    path('cart/counter/',cart_counter,name='cart-counter'),
    path('cart/updatequantity/',quantity_update, name='quantity-update'),
    path('cart/view_redeemable_coupons/',view_redeemable_coupons,name='usercoupons'),
    
]

cart/models.py
import decimal
from django.db import models
from accounts.models import MyUser
from django.db.models.signals import post_save,post_delete
from django.dispatch import receiver
from django.utils.datetime_safe import datetime
from django.contrib.sessions.models import Session

# Create your models here.
 

class Cart(models.Model):
    user = models.OneToOneField("accounts.MyUser", verbose_name="User",related_name="cart" , on_delete=models.CASCADE,null=True,)
    created_at = models.DateTimeField(auto_now=False, auto_now_add=True,)
    # total = models.DecimalField(default=0.00, max_digits=20, decimal_places=2)
    updated = models.DateTimeField(auto_now=True)
    count = models.PositiveIntegerField(default=0)
    session=models.ForeignKey(Session, on_delete=models.CASCADE,null=True)
    coupon = models.ForeignKey('coupons.UserCoupon',related_name='user_cart',on_delete = models.SET_NULL,null=True)
    
    
    def __str__(self):
        return f"This cart contains {self.count} items and its cost is {self.total}"
    def get_absolute_url(self):
        return self.id
    @property
    def total(self):
        total = decimal.Decimal(0)
        itemlist = self.items.all()
        for item in itemlist:
            total += decimal.Decimal(item.item_total) - decimal.Decimal(item.item_offer_discount)
        return total
    @property
    def final_total(self):
        return self.total - decimal.Decimal(self.coupon_discount)
    @property
    def total_no_discount(self):
        total_no_discount = 0
        itemlist = self.items.all()
        for item in itemlist:
            total_no_discount += item.item_total
        return total_no_discount
    
    @property
    def total_discount_given(self):
        total_discount_given = decimal.Decimal(0.00)
        itemlist = self.items.all()
        for item in itemlist:
            total_discount_given += decimal.Decimal(item.item_offer_discount)
        return total_discount_given

    @property
    def count(self):
        count = self.items.all().count()
        return count
    @property
    def coupon_discount(self):
        if self.coupon is not None:
            main_coupon = self.coupon.coupon
            disc_type = main_coupon.discount_type
            if disc_type == 'Percentage':
                coupon_discount = decimal.Decimal(self.total)*decimal.Decimal(main_coupon.discount_percent_value/100)
                coupon_discount = round(coupon_discount,2)
                if coupon_discount > main_coupon.max_discount_amount:
                    coupon_discount = main_coupon.max_discount_amount
                return coupon_discount
            if disc_type == 'Amount':
                coupon_discount = main_coupon.discount_amount_value
                return coupon_discount
        else:
            coupon_discount = 0.00
            return coupon_discount


class cartItem(models.Model):
    game=models.ForeignKey("products.Game", verbose_name="Game", on_delete=models.CASCADE,related_name='cartitems',null=False,blank=False)
    cart = models.ForeignKey("cart.Cart", verbose_name="cart", on_delete=models.CASCADE,related_name='items')
    updated  = models.DateTimeField(auto_now=True)
    quantity = models.IntegerField(default=1,null=False,blank=False)
    def __str__(self):
        return f"This item is {self.game.title} and its cost is {self.game.base_price}"
    
    def get_absolute_url(self):
        return self.id
    
    @property
    def item_total(self):
        item_total = self.quantity*self.game.base_price
        return item_total

    @property
    def item_offer_discount(self):
        if self.game.discount_status != "None":
            item_offer_discount = self.quantity*self.game.base_price - (self.quantity*self.game.discounted_price)
        else:
            item_offer_discount = 0.00
        return item_offer_discount
    
    @property
    def item_offer_discounted_price(self):
        if self.game.discount_status != 'None':
            item_offer_discounted_price = self.game.discounted_price*self.quantity
        else:
            item_offer_discounted_price = self.game.base_price*self.quantity
        return item_offer_discounted_price
    





templates/offers/addcategoryoffer.html
{% extends 'adminpanel/admin_dashboard.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block customhead %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
{% endblock customhead %}
{% block dynamic %}
<form action="" method = 'post'>
    {% csrf_token %}
    {{form|crispy}}
    <button type='submit' class='btn btn-success'>Submit</button>
</form>
{% endblock dynamic %}

{% block extrascript %}
<script>
   

    function change_date(){
        var date = $('#id_valid_from').val();
        var category_id = $('#id_category').val();
        console.log('hellooooo');
        $.ajax({
            
            data : {'date':date,'category_id':category_id,},
            url:"/admin_panel/offers/addcategoryoffer/change_valid_till/",
            success: function(response){
                $("#id_valid_till").prop('disabled',false);
                $("#id_valid_till").flatpickr({
                    dateFormat: "Y-m-d H:i",
                    minDate: response.start_date,
                    maxDate: response.end_date,
                    enableTime: true,
                    }
                    );
            },
            error: function(response){

            },
        });
        
      }

    
    $("#id_valid_till").flatpickr({
        dateFormat: "Y-m-d H:i",
        enableTime: true,
        
        }
        );
    $("#id_valid_till").prop('disabled',true);
    $("#id_valid_from").flatpickr({
        dateFormat: "Y-m-d H:i",
        enableTime: true,
        minDate: '{{today}}',
        }
        );


    function change_category(){
        $('#id_valid_from').val('');
        $('#id_valid_till').val('');
       
        if($("#id_category").val() == ""){
            $("#id_valid_from").prop('disabled',true);
        }
        else{
            $("#id_valid_from").prop('disabled',false);
        }
        var category_id = $('#id_category').val();
        console.log('hellooooo');
        if($("#id_category").val() != ""){
        $.ajax({
            
            data : {'category_id':category_id},
            url:"/admin_panel/offers/addcategoryoffer/change_category_option/",
            success: function(response){
                console.log(response.start_date);
                $("#id_valid_from").flatpickr({
                    dateFormat: "Y-m-d H:i",
                    minDate: response.start_date,
                    enableTime: true,
                    disable: response.disable_list,
                    }
                    );
            },
            error: function(response){

            },
        });
    }
        
    }

    function change_disc_percent(){
        var disc_percent = $("#id_discount_percentage").val();
        if(disc_percent > 60){
            $("#id_discount_percentage").val('60');
            toastr.error('Maximum value is 60')
        }
        if(disc_percent < 5){
            $("#id_discount_percentage").val('');
            toastr.error('Minimum value is 5')
        }
    }

</script>
{% endblock extrascript %}

templates/offers/addproductoffer.html
{% extends 'adminpanel/admin_dashboard.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block customhead %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
{% endblock customhead %}

{% block dynamic %}
<form action="" method = "post">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class='btn btn-success'>Sumbit</button>
</form>
{% endblock dynamic %}

{% block extrascript %}
<script>
    function change_product(){
        $("#id_valid_from").val('');
        $("#id_valid_till").val('');
        if($("#id_game").val() == ""){
            $("#id_valid_from").prop('disabled',true);
        }
        else{
            $("#id_valid_from").prop('disabled',false);
        }
        var game_id = $('#id_game').val();
        console.log('hellooooo');
        if($("#id_game").val() != ""){
        $.ajax({
            
            data : {'game_id':game_id},
            url:"/admin_panel/offers/addproductoffer/change_game_option/",
            success: function(response){
                console.log(response.start_date);
                $("#id_valid_from").flatpickr({
                    dateFormat: "Y-m-d H:i",
                    minDate: response.start_date,
                    enableTime: true,
                    disable: response.disable_list,
                    }
                    );
            },
            error: function(response){

            },
        });
    }
    }

    $("#id_valid_from").flatpickr({
        dateFormat: "Y-m-d H:i",
        enableTime: true,
        minDate: '{{today}}',
        });
    $("#id_valid_till").flatpickr({
        dateFormat: "Y-m-d H:i",
        enableTime: true,
        });
    $("#id_valid_till").prop('disabled',true)

    function change_date_game(){
        var date = $('#id_valid_from').val();
        var game_id = $('#id_game').val();
        console.log('hellooooo');
        $.ajax({
            
            data : {'date':date,'game_id':game_id,},
            url:"/admin_panel/offers/addproductoffer/change_valid_till/",
            success: function(response){
                $("#id_valid_till").prop('disabled',false);
                $("#id_valid_till").flatpickr({
                    dateFormat: "Y-m-d H:i",
                    minDate: response.start_date,
                    maxDate: response.end_date,
                    enableTime: true,
                    
            
                    }
                    );
            },
            error: function(response){

            },
        });
        
    }

    function change_disc_percent(){
        var disc_percent = $("#id_discount_percentage").val();
        if(disc_percent > 60){
            $("#id_discount_percentage").val('60');
            toastr.error('Maximum value is 60')
        }
        if(disc_percent < 5){
            $("#id_discount_percentage").val('');
            toastr.error('Minimum value is 5')
        }
    }


</script>
{% endblock extrascript %}

templates/offers/editcategoryoffer.html
{% extends 'adminpanel/admin_dashboard.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block customhead %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
{% endblock customhead %}
{% block dynamic %}
<form action="" method = 'post'>
    {% csrf_token %}
    {{form|crispy}}
    <button type='submit' class='btn btn-success'>Submit</button>
</form>
{% endblock dynamic %}

{% block extrascript %}
<script>
   

    function change_date(){
        var date = $('#id_valid_from').val();
        var category_id = $('#id_category').val();
        console.log('hellooooo');
        $.ajax({
            
            data : {'date':date,'category_id':category_id,},
            url:"/admin_panel/offers/addcategoryoffer/change_valid_till/",
            success: function(response){
                $("#id_valid_till").prop('disabled',false);
                $("#id_valid_till").flatpickr({
                    dateFormat: "Y-m-d H:i",
                    minDate: response.start_date,
                    maxDate: response.end_date,
                    enableTime: true,
                    
            
                    }
                    );
            },
            error: function(response){

            },
        });
        
      }

    
    $("#id_valid_till").flatpickr({
        dateFormat: "Y-m-d H:i",
        enableTime: true,
        minDate: "{{start_date_valid_till}}",
        maxDate: "{{max_date_valid_till}}",
        disable: {{disable_list|safe}},
        }
        );

    $("#id_valid_from").flatpickr({
        dateFormat: "Y-m-d H:i",
        enableTime: true,
        minDate: "{{start_date}}",
        disable: {{disable_list|safe}},

        }
        );
    
    

    function change_category(){
        offer_edit_id = {{offer_edit_id}}
        console.log(offer_edit_id);
        var category_id = $('#id_category').val();
        console.log('hellooooo');
        $.ajax({
            
            data : {'category_id':category_id,'offer_edit_id':offer_edit_id},
            url:"/admin_panel/offers/addcategoryoffer/change_category_option/",
            success: function(response){
                console.log(response.start_date);
                $("#id_valid_from").flatpickr({
                    dateFormat: "Y-m-d H:i",
                    minDate: response.start_date,
                    enableTime: true,
                    disable: response.disable_list,
                    }
                    );
            },
            error: function(response){

            },
        });
        
      }
    
      function change_disc_percent(){
        var disc_percent = $("#id_discount_percentage").val();
        if(disc_percent > 60){
            $("#id_discount_percentage").val('60');
            toastr.error('Maximum value is 60')
        }
        if(disc_percent < 5){
            $("#id_discount_percentage").val('');
            toastr.error('Minimum value is 5')
        }
    }

</script>
{% endblock extrascript %}

templates/offers/editproductoffer.html
{% extends 'adminpanel/admin_dashboard.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block customhead %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
{% endblock customhead %}
{% block dynamic %}
<form action="" method = 'post'>
    {% csrf_token %}
    {{form|crispy}}
    <button type='submit' class='btn btn-success'>Submit</button>
</form>
{% endblock dynamic %}

{% block extrascript %}
<script>
   

    function change_date_game(){
        var date = $('#id_valid_from').val();
        var game_id = $('#id_category').val();
        console.log('hellooooo');
        $.ajax({
            
            data : {'date':date,'game_id':game_id,},
            url:"/admin_panel/offers/addproductoffer/change_valid_till/",
            success: function(response){
                $("#id_valid_till").prop('disabled',false);
                $("#id_valid_till").flatpickr({
                    dateFormat: "Y-m-d H:i",
                    minDate: response.start_date,
                    maxDate: response.end_date,
                    enableTime: true,
                    
            
                    }
                    );
            },
            error: function(response){

            },
        });
        
      }

    
    $("#id_valid_till").flatpickr({
        dateFormat: "Y-m-d H:i",
        enableTime: true,
        minDate: "{{start_date_valid_till}}",
        maxDate: "{{max_date_valid_till}}",
        disable: {{disable_list|safe}},
        }
        );

    $("#id_valid_from").flatpickr({
        dateFormat: "Y-m-d H:i",
        enableTime: true,
        minDate: "{{start_date}}",
        disable: {{disable_list|safe}},

        }
        );
    
    

    function change_product(){
        offer_edit_id = {{offer_edit_id}}
        console.log(offer_edit_id);
        var category_id = $('#id_game').val();
        console.log('hellooooo');
        $.ajax({
            
            data : {'game_id':game_id,'offer_edit_id':offer_edit_id},
            url:"/admin_panel/offers/addproductoffer/change_game_option/",
            success: function(response){
                console.log(response.start_date);
                $("#id_valid_from").flatpickr({
                    dateFormat: "Y-m-d H:i",
                    minDate: response.start_date,
                    enableTime: true,
                    disable: response.disable_list,
                    }
                    );
            },
            error: function(response){

            },
        });
        
      }


      function change_disc_percent(){
        var disc_percent = $("#id_discount_percentage").val();
        if(disc_percent > 60){
            $("#id_discount_percentage").val('60');
            toastr.error('Maximum value is 60')
        }
        if(disc_percent < 5){
            $("#id_discount_percentage").val('');
            toastr.error('Minimum value is 5')
        }
    }
    
</script>
{% endblock extrascript %}

templates/offers/offerlist.html
{% extends 'adminpanel/admin_dashboard.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block dynamic_css %} <link rel="stylesheet" href="{% static 'styles/admin_offerlist.css' %}"> {% endblock dynamic_css %}
{% block customhead %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
{% endblock customhead %}
{% block dynamic %}

{% if messages %}
  {% for message in messages %}
      
      <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
      <script>
        Swal.fire({
          
          
          text: "{{message}}",
        })  
      </script>
    
  {% endfor %}
{% endif %}


<div class="row w-80 mx-1 mb-4">
    <div class="card bg-dark col-md-3 p-0 me-md-2 me-0" >
        <div class="card-header">
          Category Offer Overview
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item d-flex justify-content-between"><span>Ongoing offers</span><span>{{ongoing_category_offers_count}}</span></li>
          <li class="list-group-item d-flex justify-content-between"><span>Upcoming offers</span><span>{{upcoming_category_offers_count}}</span></li>
          <li class="list-group-item d-flex justify-content-between"><span>Expired offers</span><span>{{expired_category_offers_count}}</span></li>
        </ul>
      </div>
      <div class="card bg-dark col-md-3 p-0" >
        <div class="card-header">
          Product Offer Overview
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item d-flex justify-content-between"><span>Ongoing offers</span><span>{{ongoing_product_offers_count}}</span></li>
          <li class="list-group-item d-flex justify-content-between"><span>Upcoming offers</span><span>{{upcoming_product_offers_count}}</span></li>
          <li class="list-group-item d-flex justify-content-between"><span>Expired offers</span><span>{{expired_product_offers_count}}</span></li>
        </ul>
      </div>
</div>
<hr class='me-5'>

<h4 class='fw-bold mb-2'>Category Offers</h4>
<a href={% url 'addcategoryoffer' %}>
    <button type="button" class="btn btn-link btn-sm btn-rounded btn-addbutton">
        Add New Category Offer
    </button>
</a>
<div class='orders-contain mb-4'>
    <table id="categoryoffertable" class="display nowrap bg-dark" style="width:100%">
        <thead>
            <tr>
                <th>Offer id</th>
                <th>Offer name</th>
                <th>Category</th>
                <th>Discount Percentage</th>
                <th>Valid from</th>
                <th>Valid till</th>
                <th>Status</th>
                <th>Actions</th>
               
            </tr>
        </thead>
        <tbody>
            {% for offer in category_offers %}
            <tr>
                <td><a href="{% url 'editcategoryoffer' offer.id %}">{{offer.id}}</a></td>
                <td>{{offer.name}}</td>
                <td>{{offer.category}}</td>
                <td>{{offer.discount_percentage}}</td>
                <td>{{offer.valid_from}}</td>
                <td>{{offer.valid_till}}</td>
                <td>{{offer.status}}</td>
                <td>
                  {% if offer.status == "Upcoming" %}
                  <a style="text-decoration: none;" href= "{% url 'deletecategoryoffer' offer.id %}">
                    <i style="color:red"onclick="return confirm('Are you sure to delete '+' {{offer.name}} ?')">
                    <button type="button" class="btn btn-link btn-sm btn-rounded btn-delete">
                        Delete
                    </button></i>
                  </a>
                  {% elif offer.status == "Ongoing" %}
                  <a style="text-decoration: none;" href= "{% url 'disablecategoryoffer' offer.id %}">
                    <i style="color:red"onclick="return confirm('Are you sure you want to stop '+' {{offer.name}} ?')">
                    <button type="button" class="btn btn-link btn-sm btn-rounded btn-block">
                        Stop now
                    </button></i>
                  </a>
                  {% endif %}
                  
                </td>
                
            </tr>
            {% endfor %}
        <tbody>
    </table>
</div>

<hr class='me-5'>

<h4 class='fw-bold mb-2'>Product Offers</h4>
<a href={% url 'addproductoffer' %}>
    <button type="button" class="btn btn-link btn-sm btn-rounded btn-addbutton">
        Add New Product Offer
    </button>
</a>
<div class='orders-contain mb-4'>
    <table id="productoffertable" class="display nowrap bg-dark" style="width:100%">
        <thead>
            <tr>
                <th>Offer id</th>
                <th>Offer name</th>
                <th>Category</th>
                <th>Discount Percentage</th>
                <th>Valid from</th>
                <th>Valid till</th>
                <th>Status</th>
                <th>Actions</th>
               
            </tr>
        </thead>
        <tbody>
            {% for offer in product_offers %}
            <tr>
                <td><a href="{% url 'editproductoffer' offer.id %}">{{offer.id}}</a></td>
                <td>{{offer.name}}</td>
                <td>{{offer.category}}</td>
                <td>{{offer.discount_percentage}}</td>
                <td>{{offer.valid_from}}</td>
                <td>{{offer.valid_till}}</td>
                <td>{{offer.status}}</td>
                <td>
                  {% if offer.status == "Upcoming" %}
                  <a style="text-decoration: none;" href= "{% url 'deleteproductoffer' offer.id %}">
                    <i style="color:red"onclick="return confirm('Are you sure to delete '+' {{offer.name}} ?')">
                    <button type="button" class="btn btn-link btn-sm btn-rounded btn-delete">
                        Delete
                    </button></i>
                  </a>
                  {% elif offer.status == "Ongoing" %}
                  <a style="text-decoration: none;" href= "{% url 'disableproductoffer' offer.id %}">
                    <i style="color:red"onclick="return confirm('Are you sure you want to stop '+' {{offer.name}} ?')">
                    <button type="button" class="btn btn-link btn-sm btn-rounded btn-block">
                        Stop now
                    </button></i>
                  </a>
                  {% endif %}
                  </td>
                
            </tr>
            {% endfor %}
        <tbody>
    </table>
</div>
{% endblock dynamic %}

{% block extrascript %}
<script type="text/javascript">
    $(document).ready(function () {
      $('#categoryoffertable').DataTable({
          scrollY: 400,
          scrollX: true,
          order: [[6, 'asc']],
          columnDefs: [ {
            "targets": 6,
            render: function(data, type, row, meta) {
                if (type === 'sort') {
                  switch (data) {
                    case 'Ongoing':0
                      return 0;
                    case 'Upcoming':
                      return 1;
                    case 'Expired':
                      return 2;
                  }
                }
                
                return data;
              }
          } ],
        });
      });

      $(document).ready(function () {
        $('#productoffertable').DataTable({
            scrollY: 400,
            scrollX: true,
            order: [[6, 'asc']],
            columnDefs: [ {
                "targets": 6,
                render: function(data, type, row, meta) {
                    if (type === 'sort') {
                      switch (data) {
                        case 'Ongoing':
                          return 0;
                        case 'Upcoming':
                          return 1;
                        case 'Expired':
                          return 2;
                      }
                    }
                    
                    return data;
                  }
              } ],
          });
        });
    </script>{% endblock extrascript %}